import os
from building import *

cwd = GetCurrentDir()
objs = []

for name in sorted(os.listdir(cwd)):
    script = os.path.join(cwd, name, 'SConscript')
    if os.path.isfile(script):
        objs.extend(SConscript(os.path.join(name, 'SConscript')))

Return('objs')
