CONFIG_BSP_USING_FULL_ASSERT=y
CONFIG_USING_CPLUSPLUS=y
CONFIG_RT_MAIN_THREAD_STACK_SIZE=12288
CONFIG_RT_USING_MEMHEAP=y
CONFIG_RT_USING_DFS=y
CONFIG_RT_USING_LITTLE_FS=y
CONFIG_BLUETOOTH=y
CONFIG_BT_CON_NUM_CUSTOMIZE=y
CONFIG_CFG_MAX_BT_ACL_NUM=2
# CONFIG_BLE_GAP_CENTRAL is not set
# CONFIG_BLE_GATT_CLIENT is not set
CONFIG_BSP_BLE_CONNECTION_MANAGER=y
CONFIG_BSP_BLE_NVDS_SYNC=y
CONFIG_PKG_USING_FLASHDB=y
CONFIG_PKG_FDB_USING_FILE_POSIX_MODE=y
CONFIG_BSP_SHARE_PREFS=y
CONFIG_PKG_USING_CJSON=y
CONFIG_USING_BUTTON_LIB=y
CONFIG_DRV_EPIC_NEW_API=y
CONFIG_PKG_USING_LITTLEVGL2RTT=y
# CONFIG_BSP_USING_TOUCHD is not set
# CONFIG_LV_USING_EXT_RESOURCE_MANAGER is not set
CONFIG_LV_INDEV_DEF_READ_PERIOD=16
CONFIG_LV_IMG_CACHE_DEF_SIZE=4
CONFIG_LV_USE_FS_POSIX=y
CONFIG_LV_FS_POSIX_LETTER=65
CONFIG_LV_USE_GIF=y
CONFIG_IMAGE_CACHE_IN_PSRAM_SIZE=1048576
CONFIG_IMAGE_CACHE_IN_SRAM_SIZE=0
CONFIG_BUDDY_UI_FRONTEND_390X450=y
CONFIG_LV_FONT_MONTSERRAT_12=y
CONFIG_LV_FONT_MONTSERRAT_20=y
CONFIG_LV_FONT_MONTSERRAT_24=y
CONFIG_LV_FONT_MONTSERRAT_28=y
CONFIG_LV_FONT_MONTSERRAT_36=y
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_16=y
CONFIG_LV_USING_FREETYPE_ENGINE=y
CONFIG_LV_FB_TWO_NOT_SCREEN_SIZE=y
CONFIG_LV_FB_LINE_NUM=50
